name: Push to S3

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          m_aws_secretkey-id: ${{ secrets.M_AWS_SECRETKEY_ID }}
          to access S3 bucket key: ${{ secrets.to access S3 bucket key }}
          aws-region: us-east-1
      - name: copy files to S3 bucket
        run: |
          aws s3 cp M.txt "s3://gleanup-S3/"
